import { InterviewTask } from "./types";

// Converted from Senior_Backend_SRE_70Day_Simple.csv
export const interviewPrepData: InterviewTask[] = [
  {
    globalDay: 1,
    week: 1,
    dayOfWeek: 1,
    codingTask: "Two Sum (#1), Valid Anagram (#242), Group Anagrams (#49)",
    systemDesignTask: "Read Alex Xu 'URL Shortener'",
    infraTask: "top, ps aux, htop comparison",
    behavioralTask: "STAR: most challenging project",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 2,
    week: 1,
    dayOfWeek: 2,
    codingTask: "Longest Substring w/o Repeat (#3), Valid Palindrome (#125), Encode/Decode (#271)",
    systemDesignTask: "Draw URL shortener diagram",
    infraTask: "strace a process; note syscalls",
    behavioralTask: "STAR: critical production issue",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 3,
    week: 1,
    dayOfWeek: 3,
    codingTask: "Product Except Self (#238), Max Subarray (#53)",
    systemDesignTask: "DB schema + short code strategy",
    infraTask: "netstat -tulnp; identify listeners",
    behavioralTask: "STAR: mentoring a junior",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 4,
    week: 1,
    dayOfWeek: 4,
    codingTask: "Merge Intervals (#56), Insert Interval (#57)",
    systemDesignTask: "Scaling: replication, caching, sharding",
    infraTask: "df -h, du -sh; find disk hotspots",
    behavioralTask: "STAR: tradeoff decision",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 5,
    week: 1,
    dayOfWeek: 5,
    codingTask: "Top K Frequent (#347), Valid Parentheses (#20)",
    systemDesignTask: "Rate limiting options",
    infraTask: "/proc tour; map pid -> files",
    behavioralTask: "Review Week 1 STARs",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 6,
    week: 1,
    dayOfWeek: 6,
    codingTask: "Daily Temperatures (#739), Min Stack (#155)",
    systemDesignTask: "Mock: URL shortener",
    infraTask: "grep/awk/sed on logs",
    behavioralTask: "Practice 1 STAR aloud",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 7,
    week: 1,
    dayOfWeek: 7,
    codingTask: "Review set",
    systemDesignTask: "SD review",
    infraTask: "Practice all commands",
    behavioralTask: "Weekly reflection",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 8,
    week: 2,
    dayOfWeek: 1,
    codingTask: "Best Time to Buy (#121), Longest Repeating Char Replace (#424)",
    systemDesignTask: "Read 'Dropbox'",
    infraTask: "dig & nslookup 3 domains",
    behavioralTask: "STAR: disagreement",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 9,
    week: 2,
    dayOfWeek: 2,
    codingTask: "Min Window Substring (#76), Permutation in String (#567)",
    systemDesignTask: "Dropbox architecture: sync model",
    infraTask: "openssl s_client cert & chain",
    behavioralTask: "Review stories",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 10,
    week: 2,
    dayOfWeek: 3,
    codingTask: "Subarray Sum=K (#560), Longest K Distinct (#340)",
    systemDesignTask: "Metadata store + chunking",
    infraTask: "tcpdump: capture handshake",
    behavioralTask: "STAR: outage leadership",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 11,
    week: 2,
    dayOfWeek: 4,
    codingTask: "Find All Anagrams (#438), Sliding Window Max (#239)",
    systemDesignTask: "Conflict resolution (CRDT vs LWW)",
    infraTask: "Explain TCP 3-way handshake",
    behavioralTask: "Practice STAR",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 12,
    week: 2,
    dayOfWeek: 5,
    codingTask: "Move Zeroes (#283), Container With Most Water (#11)",
    systemDesignTask: "Scaling: LB + CDN",
    infraTask: "ping + traceroute; compare hops",
    behavioralTask: "Weekly story review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 13,
    week: 2,
    dayOfWeek: 6,
    codingTask: "Timed set",
    systemDesignTask: "Mock Dropbox",
    infraTask: "Diagnose mock network issue",
    behavioralTask: "Mock story",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 14,
    week: 2,
    dayOfWeek: 7,
    codingTask: "Weekly review",
    systemDesignTask: "Weekly review",
    infraTask: "Networking recap",
    behavioralTask: "Weekly reflection",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 15,
    week: 3,
    dayOfWeek: 1,
    codingTask: "Binary search drills; rotated array",
    systemDesignTask: "Read 'Slack'; delivery guarantees",
    infraTask: "Docker hello-world; build a tiny app",
    behavioralTask: "STAR: performance",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 16,
    week: 3,
    dayOfWeek: 2,
    codingTask: "Median of arrays; kth largest",
    systemDesignTask: "Presence + pub/sub",
    infraTask: "docker ps/exec; multi-container (compose)",
    behavioralTask: "Practice",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 17,
    week: 3,
    dayOfWeek: 3,
    codingTask: "2D matrix; min in rotated array",
    systemDesignTask: "Sharding, queues",
    infraTask: "Docker networking basics",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 18,
    week: 3,
    dayOfWeek: 4,
    codingTask: "Time-based KV; partition problems",
    systemDesignTask: "Fault tolerance & retries",
    infraTask: "Push image to registry",
    behavioralTask: "Cross-team",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 19,
    week: 3,
    dayOfWeek: 5,
    codingTask: "Timed set (1H+1M)",
    systemDesignTask: "Mock Slack design",
    infraTask: "Lab recap",
    behavioralTask: "Mock STAR",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 20,
    week: 3,
    dayOfWeek: 6,
    codingTask: "Weekly review",
    systemDesignTask: "Weekly review",
    infraTask: "Weekly recap",
    behavioralTask: "Reflect",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 21,
    week: 3,
    dayOfWeek: 7,
    codingTask: "Review weak problems",
    systemDesignTask: "SD review",
    infraTask: "Lab recap",
    behavioralTask: "Weekly reflection",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 22,
    week: 4,
    dayOfWeek: 1,
    codingTask: "Tree depth, same tree",
    systemDesignTask: "Read 'Metrics Collector'",
    infraTask: "Install minikube/kind",
    behavioralTask: "Incident triage",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 23,
    week: 4,
    dayOfWeek: 2,
    codingTask: "Level order, islands",
    systemDesignTask: "Ingestion pipeline",
    infraTask: "kubectl get/describe",
    behavioralTask: "Practice",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 24,
    week: 4,
    dayOfWeek: 3,
    codingTask: "Validate BST, subtree",
    systemDesignTask: "Time-series schema",
    infraTask: "Create Pod+Service",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 25,
    week: 4,
    dayOfWeek: 4,
    codingTask: "Clone graph, course schedule",
    systemDesignTask: "Alerting design",
    infraTask: "kubectl logs/exec",
    behavioralTask: "On-call",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 26,
    week: 4,
    dayOfWeek: 5,
    codingTask: "Course schedule II, pacific atlantic",
    systemDesignTask: "Scrape targets + federation",
    infraTask: "Deployments + rollout",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 27,
    week: 4,
    dayOfWeek: 6,
    codingTask: "Timed set",
    systemDesignTask: "Mock Prometheus",
    infraTask: "NodePort expose + test",
    behavioralTask: "Mock STAR",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 28,
    week: 4,
    dayOfWeek: 7,
    codingTask: "Weekly review",
    systemDesignTask: "Review",
    infraTask: "K8s recap",
    behavioralTask: "Reflect",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 29,
    week: 5,
    dayOfWeek: 1,
    codingTask: "TopK, kth largest",
    systemDesignTask: "Read 'Job Scheduler'",
    infraTask: "AWS EC2 basics",
    behavioralTask: "Cost optimization",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 30,
    week: 5,
    dayOfWeek: 2,
    codingTask: "Merge K lists, median stream",
    systemDesignTask: "Scheduling algorithms",
    infraTask: "S3 basics",
    behavioralTask: "Practice",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 31,
    week: 5,
    dayOfWeek: 3,
    codingTask: "IPO, task scheduler",
    systemDesignTask: "Cron-like triggers",
    infraTask: "IAM basics",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 32,
    week: 5,
    dayOfWeek: 4,
    codingTask: "K pairs, sliding window median",
    systemDesignTask: "Retries/backoff",
    infraTask: "EC2 SSH",
    behavioralTask: "Security improvement",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 33,
    week: 5,
    dayOfWeek: 5,
    codingTask: "Sliding window max, topK words",
    systemDesignTask: "Backpressure",
    infraTask: "S3 lifecycle",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 34,
    week: 5,
    dayOfWeek: 6,
    codingTask: "Timed set",
    systemDesignTask: "Mock Scheduler",
    infraTask: "IAM least privilege",
    behavioralTask: "Mock STAR",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 35,
    week: 5,
    dayOfWeek: 7,
    codingTask: "Weekly review",
    systemDesignTask: "Review",
    infraTask: "AWS recap",
    behavioralTask: "Reflect",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 36,
    week: 6,
    dayOfWeek: 1,
    codingTask: "Permutations, combination sum",
    systemDesignTask: "Read 'Notification Service'",
    infraTask: "Helm basics",
    behavioralTask: "Process improvement",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 37,
    week: 6,
    dayOfWeek: 2,
    codingTask: "Subsets, palindrome partition",
    systemDesignTask: "Push vs pull",
    infraTask: "Package & deploy chart",
    behavioralTask: "Practice",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 38,
    week: 6,
    dayOfWeek: 3,
    codingTask: "Gen parentheses, N-Queens",
    systemDesignTask: "Multi-channel design",
    infraTask: "Kustomize overlays",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 39,
    week: 6,
    dayOfWeek: 4,
    codingTask: "Sudoku, word search",
    systemDesignTask: "Fanout + retries",
    infraTask: "ConfigMaps & Secrets",
    behavioralTask: "Mentoring",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 40,
    week: 6,
    dayOfWeek: 5,
    codingTask: "Timed set",
    systemDesignTask: "Mock Notification",
    infraTask: "Secret rotation",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 41,
    week: 6,
    dayOfWeek: 6,
    codingTask: "Weekly review",
    systemDesignTask: "Review",
    infraTask: "Helm/Kustomize recap",
    behavioralTask: "Reflect",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 42,
    week: 6,
    dayOfWeek: 7,
    codingTask: "Rest",
    systemDesignTask: "Rest",
    infraTask: "Rest",
    behavioralTask: "Rest",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 43,
    week: 7,
    dayOfWeek: 1,
    codingTask: "Climbing stairs, house robber",
    systemDesignTask: "Read 'Search System'",
    infraTask: "K8s controllers 101",
    behavioralTask: "Large-scale migration",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 44,
    week: 7,
    dayOfWeek: 2,
    codingTask: "Coin change, LIS",
    systemDesignTask: "Indexing/sharding",
    infraTask: "Create a CRD",
    behavioralTask: "Practice",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 45,
    week: 7,
    dayOfWeek: 3,
    codingTask: "LCS, edit distance",
    systemDesignTask: "Query parsing",
    infraTask: "Operator SDK scaffold",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 46,
    week: 7,
    dayOfWeek: 4,
    codingTask: "Max subarray (DP), interleaving",
    systemDesignTask: "Replication/failover",
    infraTask: "Simple reconcile loop",
    behavioralTask: "Innovation",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 47,
    week: 7,
    dayOfWeek: 5,
    codingTask: "Timed set",
    systemDesignTask: "Mock Search",
    infraTask: "Finalizers & reconcile",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 48,
    week: 7,
    dayOfWeek: 6,
    codingTask: "Weekly review",
    systemDesignTask: "Review",
    infraTask: "Controllers recap",
    behavioralTask: "Reflect",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 49,
    week: 7,
    dayOfWeek: 7,
    codingTask: "Rest",
    systemDesignTask: "Rest",
    infraTask: "Rest",
    behavioralTask: "Rest",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 50,
    week: 8,
    dayOfWeek: 1,
    codingTask: "Trap rain water, min window",
    systemDesignTask: "Read 'Video Streaming'",
    infraTask: "Prometheus metrics",
    behavioralTask: "Customer impact",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 51,
    week: 8,
    dayOfWeek: 2,
    codingTask: "Median stream, serialize tree",
    systemDesignTask: "CDN + ABR",
    infraTask: "Grafana dashboard",
    behavioralTask: "Practice",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 52,
    week: 8,
    dayOfWeek: 3,
    codingTask: "2D trapping, max path sum",
    systemDesignTask: "Segment retries, multi-CDN",
    infraTask: "OpenTelemetry tracing",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 53,
    week: 8,
    dayOfWeek: 4,
    codingTask: "Timed hard set",
    systemDesignTask: "Mock Video Streaming",
    infraTask: "Logs pipeline",
    behavioralTask: "Stakeholder mgmt",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 54,
    week: 8,
    dayOfWeek: 5,
    codingTask: "Review",
    systemDesignTask: "Review",
    infraTask: "Observability recap",
    behavioralTask: "Reflect",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 55,
    week: 8,
    dayOfWeek: 6,
    codingTask: "Rest",
    systemDesignTask: "Rest",
    infraTask: "Rest",
    behavioralTask: "Rest",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 56,
    week: 8,
    dayOfWeek: 7,
    codingTask: "Rest",
    systemDesignTask: "Rest",
    infraTask: "Rest",
    behavioralTask: "Rest",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 57,
    week: 9,
    dayOfWeek: 1,
    codingTask: "Timed set",
    systemDesignTask: "Read 'Rate Limiter'",
    infraTask: "SLO/SLI/SLA",
    behavioralTask: "Risk management",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 58,
    week: 9,
    dayOfWeek: 2,
    codingTask: "Timed set",
    systemDesignTask: "Token vs leaky; API/global",
    infraTask: "Write SLO doc",
    behavioralTask: "Practice",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 59,
    week: 9,
    dayOfWeek: 3,
    codingTask: "Timed set",
    systemDesignTask: "Distributed limits",
    infraTask: "Error budgets & policy",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 60,
    week: 9,
    dayOfWeek: 4,
    codingTask: "Timed set",
    systemDesignTask: "Mock Rate Limiter",
    infraTask: "Incident drill & postmortem",
    behavioralTask: "Postmortem leadership",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 61,
    week: 9,
    dayOfWeek: 5,
    codingTask: "Review",
    systemDesignTask: "Review",
    infraTask: "Reliability recap",
    behavioralTask: "Reflect",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 62,
    week: 9,
    dayOfWeek: 6,
    codingTask: "Rest",
    systemDesignTask: "Rest",
    infraTask: "Rest",
    behavioralTask: "Rest",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 63,
    week: 9,
    dayOfWeek: 7,
    codingTask: "Rest",
    systemDesignTask: "Rest",
    infraTask: "Rest",
    behavioralTask: "Rest",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 64,
    week: 10,
    dayOfWeek: 1,
    codingTask: "Weak area drill",
    systemDesignTask: "Read 'CI/CD System'",
    infraTask: "IAM best practices",
    behavioralTask: "Culture change",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 65,
    week: 10,
    dayOfWeek: 2,
    codingTask: "Weak area drill",
    systemDesignTask: "Pipeline stages",
    infraTask: "Vault basics",
    behavioralTask: "Practice",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 66,
    week: 10,
    dayOfWeek: 3,
    codingTask: "Weak area drill",
    systemDesignTask: "Scaling runners & caching",
    infraTask: "Secret rotation",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 67,
    week: 10,
    dayOfWeek: 4,
    codingTask: "Mock: coding + SD",
    systemDesignTask: "Mock CI/CD",
    infraTask: "Mock security incident",
    behavioralTask: "Conflict resolution",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 68,
    week: 10,
    dayOfWeek: 5,
    codingTask: "Review",
    systemDesignTask: "Review",
    infraTask: "Review",
    behavioralTask: "Review",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 69,
    week: 10,
    dayOfWeek: 6,
    codingTask: "Final mock loop",
    systemDesignTask: "Final mock loop",
    infraTask: "Final mock loop",
    behavioralTask: "Final mock loop",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  },
  {
    globalDay: 70,
    week: 10,
    dayOfWeek: 7,
    codingTask: "Light review & rest",
    systemDesignTask: "Light review & rest",
    infraTask: "Light review & rest",
    behavioralTask: "Light review & rest",
    doneCoding: false,
    doneSD: false,
    doneInfra: false,
    doneBehavioral: false,
    notes: ""
  }
];

export const getDayOfWeekName = (dayOfWeek: number): string => {
  const days = ["", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
  return days[dayOfWeek] || "";
};

export const getTaskIcon = (type: string): string => {
  switch (type) {
    case 'coding': return '💻';
    case 'systemDesign': return '🏗️';
    case 'infra': return '⚙️';
    case 'behavioral': return '🎯';
    default: return '📝';
  }
};
